### ISSUE TITLE
Upgrade heroku stack

### ISSUE THREAD

**Issue by Marri** [glowfic-constellation/glowfic#1495]
We're on heroku-16 which unpacks to ubuntu 16 and this hits EOL in the spring and we should knock it off

**Comment by Throne3d** [comment]
This seems like it should be straightforward – buildpacks aren't impacted, and the main difference is the underlying OS used (Ubuntu 20.04 instead of 16.04). Heroku recommends [testing the new stack in a new app](https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack#testing-an-app-on-a-new-stack), which we could use the staging app for, but should just be that!

**Comment by Throne3d** [comment]
Done
